### ISSUE TITLE
`mlflow` health endpoint is doutbful

### ISSUE THREAD

**Issue by pebeto** [JuliaAI/MLJFlow.jl#34]
`mlflow` local instances provide `/health` and `/ping` endpoints to check if it is running. Platforms like `DagsHub` don't have it (well, as far as I have been able to test), making users being unable to use this package. Should we remove that check?

**Comment by pebeto** [comment]
If we are not going to remove this check, we must search a way to detect if the provided URI is a valid mlflow instance.

**Comment by ablaom** [comment]
Just to be clear,  are you saying the current health checks don't use public API? 

And this has gotten us into trouble, because our checks are crashing sessions via DagsHub?

If the answer to both questions is "yes" then I agree we need to remove the check. In any case, this ought to be something we implement at MLFlowClient.jl, yes? I don't how to officially check instance health, but we could post a question at mljflow.

**Comment by pebeto** [comment]
The current `healthcheck` is using a non REST endpoint to show  `mlflow` instance status. This endpoint is enabled by default with the common distribution. However, platforms like `DagsHub` removed it by unknown reasons. So, yes to both questions.

We need to request a `healthcheck` inside the REST API to have an official way to do this. If that's not the case, we can play with the webpage to extract certain parts to ensure an instance (but that's awful).
